version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
  inspect:
    docker:
       - image: cimg/base:2023.03
    resource_class: small
    environment:
      WEBHOOK_BODY: << pipeline.trigger_parameters.webhook.body >>
    steps:
      - run: echo "Hello :)"
      - run: 
          command: |
            echo "export AUTHOR_ASSOCIATION=$(echo ${WEBHOOK_BODY} | jq -r '.issue.author_association')" >> $BASH_ENV
            echo "export MESSAGE=$(${WEBHOOK_BODY}  | jq -r '.comment.body')" >> $BASH_ENV
            echo "export USERNAME=$(${WEBHOOK_BODY}  | jq -r '.issue.user.login')" >> $BASH_ENV
            source $BASH_ENV
            echo ${AUTHOR_ASSOCIATION} SPACE ${MESSAGE} SPACE  ${USERNAME}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - inspect
      - build:
          requires:
            - "inspect"
      - test:
          requires:
            - build