version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
  inspect:
    docker:
       - image: cimg/base:2023.03
    resource_class: small
    steps:
      - run: echo "Hello :)"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - inspect
      - build:
          requires:
            - "inspect"
      - test:
          requires:
            - build